# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sprockets-rails}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jeffkreeftmeijer"]
  s.date = %q{2009-11-30}
  s.description = %q{sprockets-rails}
  s.email = %q{jeff@80beans.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "config/sprockets.yml",
     "init.rb",
     "install.rb",
     "lib/sprocket.rb",
     "lib/sprockets-rails.rb",
     "lib/sprockets_application.rb",
     "lib/sprockets_controller.rb",
     "lib/sprockets_helper.rb",
     "recipes/sprockets_tasks.rb",
     "sprockets-rails.gemspec",
     "tasks/sprockets_tasks.rake",
     "test/sprockets_test.rb"
  ]
  s.homepage = %q{http://github.com/80beans/sprockets-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{sprockets-rails}
  s.test_files = [
    "test/sprockets_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
